server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    ip-address: localhost
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servico-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/clientes/**
        - id: servicio-foto
          uri: lb://servicio-foto
          predicates:
            - Path=/fotos/**